### ISSUE TITLE
About Checkpoint

### ISSUE THREAD

**Issue by kimm51** [hellopipu/PromptMR#2]
Hello,

Is it possible to share 4x acceleration knee checkpoint ? I want to compare it with ensemble methods and prospective other tasks.

Thanks,

**Comment by hellopipu** [comment]
The training for both 4x and 8x accelerations is currently in progress. I plan to finish this training and release the checkpoint in one week.

**Comment by kimm51** [comment]
Hello, 

Did you finish training for 4x and 8x ?

Best,

**Comment by hellopipu** [comment]
Hi @kimm51 ,  I just uploaded the model. see [here](https://github.com/hellopipu/PromptMR/tree/main/promptmr_examples/fastmri).

**Comment by kimm51** [comment]
Thank you very much!
