### ISSUE TITLE
About Acceleration Rates

### ISSUE THREAD

**Issue by efox94** [hellopipu/PromptMR#3]
Hello,

In the context of both cardiac and knee challenges, there are multiple acceleration rates available. For cardiac scans, there are 4, 8, and 10-fold accelerated scans, and for knee scans, there are 4 and 8-fold accelerated scans. I'm seeking clarification on the training and testing procedure for the network:

Was the network trained exclusively with 4-fold accelerated scans and then tested with 4, 8, and 10-fold accelerated scans?

Or, was the network trained with 4-fold accelerated scans and tested only with 4-fold accelerated test scans?

Additionally, I'd like to know if the same approach extends to other acceleration rates.

Thank you,

**Comment by hellopipu** [comment]
The released models for the CMRxRecon dataset have been trained with acceleration factors of 4, 8, and 10.

The model currently released for the multi-coil knee dataset was trained and tested solely with an acceleration factor of 8 to allow for a fair comparison with HUMUS-Net, which provides pre-trained model only at this acceleration factor. We intend to release the model trained with acceleration factors of 4 and 8 soon.

In general, our approach should be to train a single model on all available acceleration factors for the given dataset.
